# We added this to avoid a separate title coming on top with our name "Srinivasa Reddy Eda" hyperlinked.
title: " "
description: "My Professional Portfolio"
theme: jekyll-theme-cayman # or whatever theme you prefer